# Generated by Django 2.0.6 on 2018-06-27 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0002_auto_20180628_0129'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Userinfo',
        ),
    ]
