# Generated by Django 2.0.6 on 2018-06-28 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0004_userinfo_total_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='oauth_token_secret',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
